### PR TITLE
Resolve broken link path language_concepts/assert.

### PR DESCRIPTION
**Pull request by burke-md**
# Description

This PR resolves a broken link to the update in constrain/assert syntax information.

## Problem\*

The file path in the link has been corrected.

Resolves 
[Issue 190](https://github.com/noir-lang/docs/issues/190)
## Summary\*

On [this](https://noir-lang.org/language_concepts/constrain/) page you can click the `assert` link within the red danger box and observe the broken link. 
Before:

```
Link redirected to Page Not Found.
```

After:

```
Link redirects to appropriate content.
```

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by critesjosh** [comment]
I am able to reproduce the error intermittently, but I am not sure that this is the proper fix for this since the relative path from `05_constrain.md` to `assert.md` is not `../language_concepts/assert`. I am unable to reproduce on Chrome, able to on Firefox.

I cannot reproduce this with a local build, I can only see it on the production site. Perhaps updating to `assert` will work, rather than `./assert`?

**Comment by critesjosh** [comment]
I updated the relative path to `assert` in this [PR](https://github.com/noir-lang/docs/pull/193). It seems to be working for me. 

Can you try to reproduce the error?

**Comment by burke-md** [comment]
@critesjosh It looks like you've merged this fix into production. 

As of 7:30 PM EST The link works as expected in Chrome, but not in Brave browser. Both tested w/ cleared cache. 

Additionally I was not able to re-create the error locally in any browser. 

In Brave it is taking me to `https://noir-lang.org/language_concepts/constrain/assert`
Perhaps you could confirm if this is the case in Firefox as well?

**Comment by critesjosh** [comment]
I think I got it working with by updating the markdown link to:  `[assert](./04_assert.md)`

**Pull request merged**
