### PR TITLE
chore: Document LSP

### LINKED ISSUE #187: Document the `nargo lsp` command
Document PR [#1560](https://github.com/noir-lang/noir/pull/1560) on the Noir repository.

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #187 

## Summary\*

This documents the `nargo lsp` command and adds a section to Getting Started that explains the components and how to install the LSP (and configure if necessary).

This might need some workshopping.

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by phated** [comment]
Currently a draft because I need to publish the LSP extension

**Comment by signorecello** [comment]
thank you so much @phated

**Comment by phated** [comment]
I've updated this with the marketplace URL and resolved the conflicts. This should be good for review and revisions!

**Review by signorecello — APPROVED** [review]
Perfect, just installed it and it works perfectly. Nice docs as well, thanks!

**Pull request merged**
